#ifndef MARLIGHTCONTROLLER_GLOBAL_H
#define MARLIGHTCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MARLIGHTCONTROLLER_LIBRARY)
#  define MARLIGHTCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MARLIGHTCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MARLIGHTCONTROLLER_GLOBAL_H
